language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

matrix:
  include:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
  fast_finish: true
  allow_failures:
      - php: hhvm

before_install:
    # Disable XDebug speed up test execution. (Ignore failures if platform does not had the extension installed)
    - phpenv config-rm xdebug.ini || return 0
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || return 0
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini || return 0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --ignore-platform-reqs
  - travis_retry composer update --prefer-source --no-interaction --dev

script:
  - ls
  - phpunit

branches:
  only:
      - master
      - develop

services:
    - mongodb
    - elasticsearch
